repos:
-   repo: local
    hooks:
    -   id: terraform_format
        name: terraform_format
        entry: -d hashicorp/terraform:1.5.2 fmt
        language: docker_image
-   repo: local
    hooks:
    -   id: terraform_validate
        name: terraform_validate
        entry: -d hashicorp/terraform:1.5.2 validate
        language: docker_image
-   repo: local
    hooks:
    -   id: terraform_lint
        name: terraform_lint
        entry: -d ghcr.io/terraform-linters/tflint:v0.47.0
        language: docker_image
-   repo: local
    hooks:
    -   id: tfsec
        name: tfsec
        entry: -d aquasec/tfsec:v1.28
        language: docker_image                         
-   repo: local
    hooks:
    -   id: terraform_apply
        name: terraform_apply
        entry: --entrypoint /src/hooks/validate_tfvars.sh zenika/terraform-azure-cli
        language: docker_image

