# Rerun `pre-commit install` after every update of this file
# repos:
# -   repo: https://github.com/antonbabenko/pre-commit-terraform
#     rev: v1.81.0
#     hooks:
#     -   id: terraform_fmt
#     -   id: terraform_validate
    # -   id: terraform_tflint
    #     args:
    #       - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    # -   id: terraform_tfsec
        #azure-container-limit-authorized-ips excluded until https://github.com/aquasecurity/trivy/discussions/4331 is solved
        # args:
        # - --args=--format json 
            # -e azure-container-limit-authorized-ips        
            # -m CRITICAL
repos:
# -   repo: local
#     hooks:
#     -   id: terraform_validate
#         name: terraform_validate
#         entry: hashicorp/terraform:1.5.2 validate
#         language: docker_image            
-   repo: local
    hooks:
    -   id: terraform_apply
        name: terraform_apply
        entry: --entrypoint /src/hooks/validate_tfvars.sh zenika/terraform-azure-cli
        language: docker_image

